namespace GodotSteam;


public enum HtmlMouseCursor
{
    User = 0,
    None = 1,
    Arrow = 2,
    Ibeam = 3,
    HourGlass = 4,
    WaitArrow = 5,
    Crosshair = 6,
    Up = 7,
    SizeNw = 8,
    SizeSe = 9,
    SizeNe = 10,
    SizeSw = 11,
    SizeW = 12,
    SizeE = 13,
    SizeN = 14,
    SizeS = 15,
    SizeWe = 16,
    SizeNs = 17,
    SizeAll = 18,
    No = 19,
    Hand = 20,
    Blank = 21,
    MiddlePan = 22,
    NorthPan = 23,
    NorthEastPan = 24,
    EastPan = 25,
    SouthEastPan = 26,
    SouthPan = 27,
    SouthWestPan = 28,
    WestPan = 29,
    NorthWestPan = 30,
    Alias = 31,
    Cell = 32,
    ColResize = 33,
    CopyCur = 34,
    VerticalText = 35,
    RowResize = 36,
    ZoomIn = 37,
    ZoomOut = 38,
    Help = 39,
    Custom = 40,
    Last = 41
}